{{- /*
Copyright 2025 New Vector Ltd

SPDX-License-Identifier: AGPL-3.0-only
*/ -}}
{{- with .Values.elementAdmin -}}
{{- if .enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "element-io.element-admin.labels" (dict "root" $ "context" .) | nindent 4 }}
  name: {{ $.Release.Name }}-element-admin
  namespace: {{ $.Release.Namespace }}
data:
  {{- include "element-io.element-admin.configmap-data" (dict "root" $) | nindent 4 -}}
{{- end }}
{{- end }}

