# Copyright 2024-2025 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

deploymentMarkers:
  enabled: false

matrixRTC:
  enabled: false

elementWeb:
  enabled: false

matrixAuthenticationService:
  enabled: false

synapse:
  enabled: false

wellKnownDelegation:
  enabled: false
