{{- /*
Copyright 2026 New Vector Ltd
Copyright 2026 Element Creations Ltd

SPDX-License-Identifier: AGPL-3.0-only
*/ -}}
{{- with $.Values.hookshot -}}
{{- if and (eq (include "element-io.ess-library.ingress.isEnabled" (dict "root" $ "context" (dict "inboundTrafficHandler" .inboundTrafficHandler "handlerType" "routes"))) "true") .routes.host -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
{{- $extraAnnotations := dict }}
{{- include "element-io.ess-library.ingress.annotations" (dict "root" $ "context" (dict "ingress" .routes "extraAnnotations" $extraAnnotations)) | nindent 2 }}
  labels:
    {{- include "element-io.hookshot.labels" (dict "root" $ "context" $.Values.haproxy) | nindent 4 }}
  name: {{ $.Release.Name }}-hookshot
  namespace: {{ $.Release.Namespace }}
spec:
  parentRefs:
    {{- include "element-io.ess-library.ingress.parentRefs" (dict "root" $ "context" (dict "serviceName" "hookshot" "routes" .routes)) | nindent 4 }}
  hostnames:
    - {{ (tpl .routes.host $) | quote }}
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /widgetapi/v1
      backendRefs:
        - name: "{{ $.Release.Name }}-hookshot"
          port: 7778
          group: ""
          kind: Service
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
        - name: "{{ $.Release.Name }}-hookshot"
          port: 7775
          group: ""
          kind: Service
    {{- if eq (include "element-io.ess-library.ingress.tls.isEnabled" (dict "root" $ "context" .routes)) "true" }}
    - matches:
      - path:
          type: PathPrefix
          value: /
      filters:
      - requestRedirect:
          scheme: https
          statusCode: 301
        type: RequestRedirect
    {{- end }}
{{- end }}
{{- end }}
