{{- /*
Copyright 2026 Element Creations Ltd

SPDX-License-Identifier: AGPL-3.0-only
*/ -}}


{{- with $.Values.hookshot -}}
{{- if .enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-hookshot
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "element-io.hookshot.labels" (dict "root" $ "context" .) | nindent 4 }}
spec:
{{ with .ingress.service.type | default $.Values.ingress.service.type }}
  type: {{ . }}
  {{ if eq . "ClusterIP" }}
  clusterIP: None
  {{- end }}
{{- end }}
  ipFamilyPolicy: PreferDualStack
  publishNotReadyAddresses: true
  ports:
  - port: 9993
    name: appservice
    protocol: TCP
  - port: 7775
    name: webhooks
    protocol: TCP
  - port: 7777
    name: metrics
    protocol: TCP
  - port: 7778
    name: widgets
    protocol: TCP
  selector:
    app.kubernetes.io/instance: "{{ $.Release.Name }}-hookshot"
{{- end -}}
{{- end -}}
