{{- /*
Copyright 2024 New Vector Ltd
Copyright 2025 Element Creations Ltd

SPDX-License-Identifier: AGPL-3.0-only
*/ -}}

{{- with $.Values.matrixRTC -}}
{{- if .enabled -}}
{{- with .sfu -}}
{{- if and .enabled .exposedServices.turnTLS.enabled (eq .exposedServices.turnTLS.portType "NodePort") -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "element-io.matrix-rtc-sfu-turn-tls.labels" (dict "root" $ "context" .) | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ $.Release.Name }}-matrix-rtc-sfu-turn-tls
  namespace: {{ $.Release.Namespace }}
spec:
  type: {{ .exposedServices.turnTLS.type }}
  ipFamilyPolicy: PreferDualStack
  externalTrafficPolicy: Local
  ports:
  - name: "turn-tls-tcp"
    protocol: "TCP"
    port: {{ .exposedServices.turnTLS.port }}
    targetPort: {{ .exposedServices.turnTLS.port }}
    nodePort: {{ .exposedServices.turnTLS.port }}
  selector:
    app.kubernetes.io/instance: "{{ $.Release.Name }}-matrix-turn-tls-sfu"
{{- end }}
{{- end }}
{{- end }}
{{- end }}
