{{- /*
Copyright 2024 New Vector Ltd
Copyright 2026 Element Creations Ltd

SPDX-License-Identifier: AGPL-3.0-only
*/ -}}

{{- with $.Values.matrixRTC -}}
{{- if .enabled -}}
{{- with .sfu -}}
{{- if and .enabled .exposedServices.turn.enabled (ne .exposedServices.turn.portType "HostPort") -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "element-io.matrix-rtc-sfu.labels" (dict "root" $ "context" (mustMergeOverwrite (dict "suffix" "-turn") .)) | nindent 4 }}
  {{- with .exposedServices.turn.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ $.Release.Name }}-matrix-rtc-sfu-turn
  namespace: {{ $.Release.Namespace }}
spec:
  type: {{ .exposedServices.turn.portType }}
  ipFamilyPolicy: PreferDualStack
  internalTrafficPolicy: {{ .exposedServices.turn.internalTrafficPolicy }}
  externalTrafficPolicy: {{ .exposedServices.turn.externalTrafficPolicy }}
  ports:
  - name: "turn-udp"
    protocol: "UDP"
    port: {{ .exposedServices.turn.port }}
    targetPort: {{ .exposedServices.turn.port }}
    nodePort: {{ .exposedServices.turn.port }}
  selector:
    app.kubernetes.io/instance: "{{ $.Release.Name }}-matrix-rtc-sfu"
{{- end }}
{{- end }}
{{- end }}
{{- end }}
