{{- /*
Copyright 2026 New Vector Ltd
Copyright 2026 Element Creations Ltd

SPDX-License-Identifier: AGPL-3.0-only
*/ -}}
{{- if and .Values.ingress.gateway .Values.ingress.gateway.create }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
{{- include "element-io.ess-library.ingress.annotations" (dict "root" $ "context" (dict "ingress" .Values.ingress.gateway)) | nindent 2 }}
  labels:
    {{- include "element-io.gateway.labels" (dict "root" $ "context" .Values.ingress.gateway) | nindent 4 }}
  name: {{ $.Release.Name }}
  namespace: {{ $.Release.Namespace }}
spec:
  gatewayClassName: {{ .Values.ingress.gateway.className }}
  listeners:
  {{- include "element-io.gateway.listeners" (dict "root" $) | nindent 4 -}}
{{- end }}
