{{- /*
Copyright 2026 Element Creations Ltd

SPDX-License-Identifier: AGPL-3.0-only
*/ -}}


{{- if (include "element-io.redis.internalRedisEnabled" (dict "root" $)) -}}
{{- with $.Values.redis -}}
{{- include "element-io.ess-library.serviceAccount" (dict "root" $ "context" (dict "componentValues" . "nameSuffix" "redis")) }}
{{- end }}
{{- end }}
