# Copyright 2024-2025 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

apiVersion: v2
name: matrix-stack
description: A Helm meta-chart for deploying a Matrix Stack from Element
type: application
version: 25.4.2-dev
dependencies: []
