# Copyright 2025 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

serverName: ess.localhost

elementAdmin:
  ingress:
    host: admin.{{ $.Values.serverName }}
    tlsSecret: "{{ $.Release.Name }}-element-admin-tls"

  replicas: 2

  annotations:
    has-no-service-monitor: "true"

  podSecurityContext:
    runAsGroup: 0
