# Copyright 2025 New Vector Ltd
# Copyright 2025-2026 Element Creations Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

hookshot:

  # Static registration file provided externally - should ignore AS_TOKEN and HS_TOKEN
  appserviceRegistration:
    secret: "{{ $.Release.Name }}-hookshot-external-registration"
    secretKey: registration.yaml