# Copyright 2025 New Vector Ltd
# Copyright 2025-2026 Element Creations Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

hookshot:

  passkey:
    secret: "{{ $.Release.Name }}-hookshot-external-passkey"
    secretKey: passfile

  # Use AS_TOKEN and HS_TOKEN instead of static registration file
  asToken:
    secret: "{{ $.Release.Name }}-hookshot-external-as-token"
    secretKey: as_token

  hsToken:
    secret: "{{ $.Release.Name }}-hookshot-external-hs-token"
    secretKey: hs_token