# Copyright 2025 New Vector Ltd
# Copyright 2025-2026 Element Creations Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

hookshot:
  passkey:
    value: |
      CHANGEME
      -----BEGIN PRIVATE KEY-----
      MIIJQQIBADANBgkqhkiG9w0BAQEFAASCCSswggknAgEAAoICAQDLtjXE9gRU9GVE
      2Kt8VQORnOOlNlPvTwosXeSvJKl0llRW3ajDqpfbHfG2BOTvnHEqfO5KQGXCwBmx
      3a0sbQ0x4upx47vOpX+zpOaF3gor
      -----END PRIVATE KEY-----

  # Use as_token and hs_token to generate a dynamic instead of static registration file
  asToken:
    value: "CHANGEME-ushi5ieMaebooJahquaechucha7Owua2"

  hsToken:
    value: "CHANGEME-cie9nehee2ohSahloh3Ahquii3ningai"
