# Copyright 2025-2026 Element Creations Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

matrixRTC:
  sfu:
    exposedServices:
      turnTLS:
        enabled: true
        # Explicitly disable TLS termination on pod for external termination
        tlsTerminationOnPod: false
