# Copyright 2025 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

matrixRTC:
  sfu:
    exposedServices:
      rtcTcp:
        port: 31000
      rtcMuxedUdp:
        port: 31001
      rtcUdp:
        enabled: true
        portRange:
          endPort: 30400
          startPort: 30000
