# Copyright 2025 New Vector Ltd
# Copyright 2025 Element Creations Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

matrixRTC:
  sfu:
    exposedServices:
      turnTLS:
        enabled: true
        domain: turn.{{ $.Values.serverName }}
        tlsSecret: turn-tls
