# Copyright 2025 Element Creations Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

synapse:
  externalRedis:
    host: "external-redis.example.com"
    port: 6379
    password:
      secret: "{{ $.Release.Name }}-redis-credentials"
      secretKey: "password"
