# Copyright 2025 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

synapse:
  additional:
      00-userconfig.yaml:
        configSecret: "{{ $.Release.Name }}-synapse-secrets"
        configSecretKey: "00-userconfig.yaml"
