# Copyright 2025 New Vector Ltd
# Copyright 2025 Element Creations Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

synapse:
  extraVolumes:
    - name: test-consenttemplates
      mountContext: both
      configMap:
        name: consenttemplates
    - name: test-synapse-saml2-mappings
      mountContext: runtime
      configMap:
        name: synapse-saml2-mappings
    - name: test-synapse-saml2-mappings-hook
      mountContext: hook
      configMap:
        name: synapse-saml2-mappings-hook

  extraVolumeMounts:
    - mountPath: "/opt/synapse/gpdr_templates/en/"
      mountContext: both
      name: test-consenttemplates
      readOnly: true
    - mountPath: "/saml2_mappings"
      mountContext: runtime
      name: test-synapse-saml2-mappings
      readOnly: true
    - mountPath: "/saml2_mappings"
      mountContext: hook
      name: test-synapse-saml2-mappings-hook
      readOnly: true
