# Copyright 2025 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

synapse:
  workers:
    account-data:
      enabled: true
    appservice:
      enabled: true
    background:
      enabled: true
    client-reader:
      enabled: true
    device-lists:
      enabled: true
    encryption:
      enabled: true
    event-creator:
      enabled: true
    event-persister:
      enabled: true
      replicas: 2
    federation-inbound:
      enabled: true
    federation-reader:
      enabled: true
    federation-sender:
      enabled: true
    initial-synchrotron:
      enabled: true
    media-repository:
      enabled: true
    presence-writer:
      enabled: true
    push-rules:
      enabled: true
    pusher:
      enabled: true
      replicas: 2
    receipts:
      enabled: true
    sliding-sync:
      enabled: true
    sso-login:
      enabled: true
    synchrotron:
      enabled: true
    typing-persister:
      enabled: true
    user-dir:
      enabled: true
