# Copyright 2025 New Vector Ltd
# Copyright 2025 Element Creations Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

wellKnownDelegation:
  ingress:
    tlsSecret: "{{ $.Release.Name }}-well-known-web-tls"

haproxy:
  podSecurityContext:
    runAsGroup: 0
